name: Build and Release CLI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            os: linux
            binary: masspr-linux-amd64
          - arch: arm64
            os: linux
            binary: masspr-linux-arm64
          - arch: amd64
            os: darwin
            binary: masspr-darwin-amd64
          - arch: arm64
            os: darwin
            binary: masspr-darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o ${{ matrix.binary }} ./cmd/masspr
          chmod +x ${{ matrix.binary }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary }}
          path: ${{ matrix.binary }}
          retention-days: 5

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/masspr-linux-amd64
            artifacts/masspr-linux-arm64
            artifacts/masspr-darwin-amd64
            artifacts/masspr-darwin-arm64
          generate_release_notes: true 